# Generated by Django 4.0.3 on 2022-04-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_store_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
