# Generated by Django 4.0.3 on 2022-04-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_order_date_order_order_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='Cart',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartitems',
            old_name='Store',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='Store',
            new_name='store',
        ),
    ]
