# Generated by Django 4.0.3 on 2022-04-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_cart_cartitems_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='store',
            new_name='Store',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='store',
            new_name='Store',
        ),
    ]
