# Generated by Django 4.0.3 on 2022-04-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_store_cartitems_store_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='cart',
            new_name='Cart',
        ),
        migrations.RenameField(
            model_name='cartitems',
            old_name='quantity',
            new_name='Quantity',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='quantity',
            new_name='Quantity',
        ),
    ]
